name: Build Godot HTML5 Export

on:
  push:
    branches: [main] # or your default branch

jobs:
  build-html5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Godot
        uses: firebelley/setup-godot@v1
        with:
          version: 4.2.2 # change to your Godot version
          use-headless: true
          export-templates: true

      - name: Build HTML5 Export
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Upload HTML5 Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-build
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
