name: Build & Deploy Godot Web

on:
  push:
    branches: [main]

jobs:
  export-html5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.0.0       # your version
          include-templates: true

      - run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
