name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0on:

permissions:
  contents: write

jobs:
  export-windows-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0       # your version
          include-templates: true
          use-dotnet: false

      - run: |
          mkdir -p build/windows
          godot --export-release "Windows Desktop" build/windows/cardbattle.exe

      - name: Upload exported build artifact
        uses: actions/upload-artifact@v4
        with:
          name: export-windows-desktop
          path: build/windows/

      - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref_name }}
                release_name: Release ${{ github.ref_name }}
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Release Asset (.exe)
              uses: actions/upload-release-asset@v1
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: build/cardbattle.exe
                asset_name: cardbattle.exe
                asset_content_type: application/octet-stream

            - name: Upload Release Asset (.pck)
              uses: actions/upload-release-asset@v1
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: build/cardbattle.pck
                asset_name: cardbattle.pck
                asset_content_type: application/octet-stream
